# Site settings
title: Blog
email: contato@deoliveiralucas.net
description: Blog sobre qualquer coisa sobre programaçao
baseurl: "http://deoliveiralucas.github.io"
url: "http://deoliveiralucas.github.io"

author:
  name     : 'Lucas de Oliveira'
  email    : conato@deoliveiralucas.net
  url      : deoliveiralucas.net
  facebook : http://facebook.com
  twitter  : http://twitter.com

github: https://github.com/deoliveiralucas
disqus_shortname: "deoliveiralucas"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
