# Site settings
title: lucas de oliveira
email: contato@deoliveiralucas.net
description: blog
baseurl: ""
url: "/"

author:
  name     : 'Lucas de Oliveira'
  email    : conato@deoliveiralucas.net
  url      : http://deoliveiralucas.net
  linkedin : https://br.linkedin.com/pub/lucas-de-oliveira/a0/b94/34
  github   : https://github.com/deoliveiralucas

github: https://github.com/deoliveiralucas
disqus_shortname: "deoliveiralucas"
google_analytics: UA-52446115-1

paginate: 6
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
